version: '3'
services:
  php:
    build: .
    image: "php:7.3-fpm"
    container_name: "laravel_sample_php"
    volumes:
      - ./sample:/var/www:cached
    links:
      - db
    depends_on:
      - db
  nginx:
    image: nginx:1.21-alpine
    container_name: "laravel_sample_nginx"
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  db:
    image: mysql:5.7
    container_name: "laravel_sample_db"
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
