version: "3.8"
services:
  serverless:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    environment:
      - ENVIROMNENT=development
      - AWS_QUEUE_URL=http://localstack:4566/000000000000/my-queue
    volumes:
      - .:/var/task:cached
  localstack:
    image: localstack/localstack
    ports:
      - "54566:4566" # LocalStackのデフォルトポート
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=ap-northeast-1
      - DEBUG=1
  redis:
    image: redis
    ports:
      - "56379:6379" # Redisのデフォルトポート
