services:
  serverless:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    environment:
      - ENVIROMNENT=development
      - AWS_QUEUE_URL=http://localstack:4566/000000000000/my-queue
    volumes:
      - .:/var/task:cached
    depends_on:
      - localstack
      - redis
  localstack:
    image: localstack/localstack:latest
    ports:
      - "54566:4566" # LocalStackのポート
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=ap-northeast-1
      - DATA_DIR=/tmp/localstack/data
  redis:
    image: redis
    ports:
      - "56379:6379" # Redisのデフォルトポート
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "58081:8081"
    depends_on:
      - redis
