service: lambda-sqs-redis-local
frameworkVersion: "3"

provider:
  name: aws
  runtime: ruby3.2
  stage: development
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
  redis_sqs_sample:
    handler: src/redis_sqs_sample.execute

plugins:
  - serverless-offline

custom:
  localstack:
    stages:
      - development
    host: http://localstack
    edgePort: 4566
    autostart: true
