version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app:cached
      - vendor-store:/app/vendor
      - php_socket:/var/run/php-fpm
    networks:
      - web
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - php_socket:/var/run/php-fpm
    networks:
      - web
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - web

volumes:
  mysql-volume:
  php_socket:
  vendor-store:

networks:
  web:
    driver: bridge
