version: "3"

services:
  db:
    build: .
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: test
volumes:
  db-store:
