version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - ./src/:/app

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8081:80
    depends_on:
      - app
    volumes:
      - ./src/:/app
