service: 'nodejs-typescript-sample'

frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-esbuild

provider:
  name: 'aws'
  runtime: 'nodejs14.x'
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'

custom:
  webpack:
    includeModules: true
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - 'aws-sdk'
    target: 'node14'
    # define: { 'require.resolve': undefined }
    platform: 'node'
    concurrency: 10

functions:
  hello:
    handler: src/functions/hello/
