version: '3.8'
services:
  dev-postgres:
    image: postgres:15.2-alpine
    ports:
      - 55432:5432
    environment:
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy
      POSTGRES_DB: dummy
    restart: always
    networks:
      - test
networks:
  test:
