version: "3.4"

services:
  serverless:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    environment:
      - ENVIROMNENT=development
    volumes:
      - .:/var/task:cached
