version: "3.4"

services:
  serverless:
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    environment:
      - ENVIROMNENT=development
    volumes:
      - .:/var/task:cached
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 53306:3306
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    cap_add:
      - SYS_NICE
